### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for OcclusionAwareGenerator:

### ISSUE THREAD

**Issue by ayutools** [adeptflax/motion-models#1]
Traceback (most recent call last):
  File "demo.py", line 144, in <module>
    generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, cpu=opt.cpu)
  File "demo.py", line 44, in load_checkpoints
    generator.load_state_dict(checkpoint['generator'])
  File "G:\SUCAI\Anaconda3\envs\PY388\lib\site-packages\torch\nn\modules\module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for OcclusionAwareGenerator:
        size mismatch for dense_motion_network.down.weight: copying a param with shape torch.Size([3, 1, 13, 13]) from checkpoint, the shape in current model is torch.Size([3, 1, 29, 29]).

**Comment by ayutools** [comment]
set sigma = 1.5 solved this problem

**Comment by celikmustafa89** [comment]
@vbqgyy which sigma?
